---
title: "read in all files"
author: "Ming Tang"
date: "6/14/2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

### combine all the counts into a single dataframe

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197320

```{r}
library(tidyverse)
library(purrr)

file1<- read_tsv("~/Downloads/GSE197320_RAW/GSM5914555_SKOV3_ALDH_Veh_Rep1_Genes_ReadCount.txt.gz",
                 col_names = FALSE)

files<- list.files("~/Downloads/GSE197320_RAW", full.names = TRUE)


samples<- basename(files) %>%
  str_replace(".+_ALDH_(.+)_Genes_ReadCount.txt.gz", "\\1")


read_count<- function(x, sample){
  df<- read_tsv(x, col_names = FALSE)
  names(df)<- c("gene", sample)
  return(df)
}

counts<- map2(files,samples,read_count)

counts_table<- purrr::reduce(counts, inner_join) 

head(counts_table)
```



```{r}
bind_cols(counts) %>%
  head()

```

### dummy files


```{r}
library(tidyr)
library(dplyr)
library(readr)
files<- list.files("~/playground", pattern = "sample[0-9].tsv", full.name=TRUE)

files

names(files)<- stringr::str_split(files, pattern = "/", simplify = TRUE)[, 5] %>%
  stringr::str_replace(".tsv", "")

files
```

use a for loop

```{r}
results<- data.frame()

for (file in files) {
  x<- read_tsv(file)
  sample_name<- stringr::str_replace(file, "/Users/tommytang/playground/", "") %>%
    stringr::str_replace(".tsv", "")
  x$sample<- sample_name
  results<- rbind(results, x)
}

results

results %>%
  tidyr::pivot_wider(names_from = sample, values_from = count)
```


use lapply

```{r}
counts<- lapply(files, read_tsv)

do.call(rbind, counts)

purrr::reduce(counts, rbind,)

## add a sample name column
read_count<- function(file){
  x<- read_tsv(file)
  sample_name<- stringr::str_replace(file, "/Users/tommytang/playground/", "") %>%
    stringr::str_replace(".tsv", "")
  x$sample<- sample_name
  return(x)
}

counts<- lapply(files, read_count)

do.call(rbind, counts)

purrr::reduce(counts, rbind)

```

use purrr::map and bind_rows 
```{r}
counts<- purrr::map(files, read_tsv)

dplyr::bind_rows(counts, .id = "sample") %>%
  tidyr::pivot_wider(names_from = sample, values_from = count)
```

```{r}
counts<- purrr::map_df(files, readr::read_tsv, .id = "sample")
```

